SET LINES 1000
SET PAGES 1000


COLUMN DESCRIPTIFCV FORMAT A5
COLUMN NOMCV FORMAT A35
COLUMN IDCV FORMAT A2
COLUMN POSTERECHERCHER FORMAT A30
COLUMN DISPONIBILITE FORMAT A3
COLUMN PHOTO FORMAT A55
COLUMN DISPONIBILITE FORMAT A20

COLUMN ADMIS FORMAT A10
COLUMN DATETRANSMISSION FORMAT A10
COLUMN TYPEPOSTE FORMAT A10


COLUMN IDCAN FORMAT A5
COLUMN NOMCAN FORMAT A15
COLUMN PRENOMCAN FORMAT A15
COLUMN MAILCAN FORMAT A50
COLUMN AGE FORMAT 99
COLUMN TELCAN FORMAT A15
COLUMN NATIONALITE FORMAT A10

COLUMN IDADR FORMAT A2
COLUMN NUMADR FORMAT A7
COLUMN LOCALITEADR FORMAT A10
COLUMN NOMRUEADR FORMAT A25
COLUMN CPADR FORMAT A5
COLUMN VILLEADR FORMAT A20
COLUMN PAYSADR FORMAT A10
COLUMN CONTINENTADR FORMAT A10

COLUMN NOMPERM FORMAT A5

COLUMN NOMCTRINT FORMAT A30

COLUMN IDSITERES FORMAT A3
COLUMN LIEN FORMAT A55

COLUMN NOMCPT FORMAT A40
COLUMN NOMCATEGORIE FORMAT A30

COLUMN NOMLANGUE FORMAT A15

COLUMN NIVEAU FORMAT A25

COLUMN IDETASCO FORMAT A5
COLUMN NOMETASCO FORMAT A60
COLUMN TELETASCO FORMAT A15
COLUMN IDFORM FORMAT A5
COLUMN SPECIALITE FORMAT A20

COLUMN IDENT FORMAT A3
COLUMN NOMENT FORMAT A35
COLUMN TELENT FORMAT A15
COLUMN MAILENT FORMAT A15
COLUMN POSTE FORMAT A20
COLUMN TYPECONTRAT FORMAT A15
COLUMN DESCRIPTIFEXP FORMAT A15
COLUMN DATEDEBUTEXP FORMAT A15
COLUMN DATEFINEXP FORMAT A15